---
layout: post
title:  Wetlab colonies - *Symbiodinium* qPCR
date:  2017-03-03 15:21:59
---

Running qPCR assays to see which *Symbiodinium* are in the colonies being held in the wetlab tanks.

```{r setup, include=FALSE}
library(labnotebookTools)
library(devtools)
knitr::opts_chunk$set(warning=F)
```

## Plate setup
```{r plates, results='asis'}
MasterMix(n=48, assays=list("CD"))

# Get sample names
knitr::knit("../2017-02-15-sampling-intact-colonies-in-wetlab/2017-02-15-sampling.csv", quiet=T)
df <- read.csv("2017-02-15-sampling.txt")

colonies <- df$Tag..
colonies <- colonies[c(1:10,18,12,11,15,14,16,17,19,13)]
samples <- paste(rep(colonies, each=3), rep(c(1,2,3), len=length(colonies)*3), sep="-")

# Set up plate 1
plate1.samples <- c(samples[1:42], "Mc16-47","Mc14-78","Ss+", "NEC1", "NEC2", "NTC")
plate1 <- qPCRlayout(samples=plate1.samples, targets="CD")
knitr::kable(plate1)

# Set up plate 2
plate2.samples <- c(samples[43:57], "NEC3", "NTC", "Mc16-47", "Mc14-78")
plate2 <- qPCRlayout(samples=plate2.samples, targets="CD")
knitr::kable(plate2)
```

## Results

### Raw data files  

#### *.eds  

[Plate 1](20170303_RK_WetlabColonies_1.eds)  
[Plate 2](20170303_RK_WetlabColonies_2.eds)  

#### *.txt  

[Plate 1](20170303_RK_WetlabColonies_1_data.txt)  
[Plate 2](20170303_RK_WetlabColonies_2_data.txt)  


## Analysis
```{r analysis, fig.height=5, fig.width=7}
# Import steponeR function
source_url("https://raw.githubusercontent.com/jrcunning/steponeR/master/steponeR.R")
# List results files
plates <- list.files(pattern = "*_data.txt", full.names = T)
# Import data using steponeR
q <- steponeR(files=plates, delim="\t", target.ratios="C.D",
               fluor.norm=list(C=2,D=0))$result
# QC data (remove amps with only one technical rep)
q$C.D <- ifelse(q$C.reps < 2, ifelse(q$D.reps < 2, NA, -Inf), ifelse(q$D.reps < 2, Inf, q$C.D))
# Calculate proportion D in each sample (=D/(C+D))
q$propD <- ifelse(is.finite(q$C.D), 1/(q$C.D+1),
                  ifelse(q$C.D > 0, 0, 1))

# Merge with colony metadata
q$Colony <- substr(q$Sample.Name, 1, 3)
df$Colony <- df$Tag..
res <- merge(df, q[,c("Colony", "Sample.Name", "propD")])[,c(1,3,7,8)]
res$Species <- as.character(res$Species)
res$Species[grep(pattern="Ofav", res$Species)] <- "Orbicella"
res$Colony <- factor(res$Colony)

# Plot results
library(lattice)
par(mfrow=c(1,3))
with(res[res$Species=="Ssid",], xyplot(propD ~ Colony, ylim=c(0,1), cex=2, main="S. siderea"))
with(res[res$Species=="Mcav",], xyplot(propD ~ Colony, ylim=c(0,1), cex=2, main="M. cavernosa"))
with(res[res$Species=="Orbicella",], xyplot(propD ~ Colony, ylim=c(0,1), cex=2, main="Orbicella"))   

```

